### ISSUE TITLE
NoClassDefFoundError: org/luaj/vm2/LuaValue

### ISSUE THREAD

**Issue by BrainStone** [Shiranuit/Computeacube#5]
Hi. With the version Computeacube-1.80pr1+v1.3 on Forge 14.23.5.2768 I get this exception, which breaks the mod:

```
java.lang.NoClassDefFoundError: org/luaj/vm2/LuaValue
        at dan200.computercraft.core.computer.Computer.initLua(Computer.java:648) ~[Computer.class:?]
        at dan200.computercraft.core.computer.Computer.access$1200(Computer.java:27) ~[Computer.class:?]
        at dan200.computercraft.core.computer.Computer$1.execute(Computer.java:759) ~[Computer$1.class:?]
        at dan200.computercraft.core.computer.ComputerThread.lambda$null$0(ComputerThread.java:108) ~[ComputerThread.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: org.luaj.vm2.LuaValue
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
        ... 5 more
```

**Comment by Shiranuit** [comment]
This should be fixed in this version: https://minecraft.curseforge.com/projects/computacube/files/2659353
